search_terms = ["Business Analyst", "Senior Business Analyst", "Product Analyst", "Systems Analyst", "BA"]
search_location = "Bengaluru, Karnataka, India"
switch_number = 30
randomize_search_order = False
sort_by = "Most recent"
date_posted = "Past week"
salary = ""
easy_apply_only = True
experience_level = ["Mid-Senior level", "Associate"]
job_type = ["Full-time"]
on_site = ["On-site", "Hybrid", "Remote"]
companies = []
location = []
industry = []
job_function = []
job_titles = []
benefits = []
commitments = []
under_10_applicants = False
in_your_network = False
fair_chance_employer = False
pause_after_filters = True
about_company_bad_words = ["Crossover"]
about_company_good_words = []
bad_words = ["US Citizen", "Security Clearance", "Polygraph"]
security_clearance = False
did_masters = False
current_experience = 7
